//Get all movies
GET http://localhost:4000/movies

###

//Get one movie by title
GET http://localhost:4000/movies/Avatar

###

//Get one movie by id
GET http://localhost:4000/movies/byId/1

###

//Creating a movie register
POST http://localhost:4000/movies
Content-Type: application/json

{
    "title": "Kung Fu Panda",
    "genre": "Adventure",
    "release_date": "2008-06-20"
}

###

//Updating a movie register by its id
PATCH http://localhost:4000/movies/4
Content-Type: application/json

{
    "title": "The TEST22",
    "genre": "Sci-Fi",
    "release_date": "1999-05-21"
}

###

//Deleting a movie register by its id
DELETE http://localhost:4000/movies/64

###

//Verifiyin the 404 message

GET http://localhost:4000/movies/admsa